# Base configs
baseurl: "https://spdemergency.github.io"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: 

# UI configs
title: "Art by SPD"
subtitle: "Artist/Microbiologist"
author: "SPD"
header:
 title: "Digital Art"
 subtitle: "by SPD"
footer:
 name: "Hey there, SPD here"
 bio: "I'm Sripradha, an artist/biologist.

		\" Do I dare disturb the universe? Do I dare to eat a peach?\"

			If you like my work feel free to check out my Posters, Art Prints and Stickers!"
 
web_design: "AJ"
social_urls:
  
  instagram: "https://www.instagram.com/spd_emergency/"
  


navs:

- title: Shop
  url:  https://sripradha.myinstamojo.com/

- title: Contact
  url: Contact.html
