# ----
# Site

title: Art by SPD
baseurl: "https://spdemergency.github.io"
url   : 'https://spdemergency.github.io'

google_analytics_key:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.jpg
description: Digital Art by SPD
author:
  name:
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Instagram
  links:
    - https://www.instagram.com/spd_emergency/

# -----
# Build

timezone: Etc/UTC

permalink: pretty

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      text_width: true
      image: /uploads/1.jpg
  -
    scope:
      path: "index.html"
    values:
      text_width: false

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
  image:
    width: 2048
    height: 1365
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true